import { Vuepress } from '@vuepress/client/lib/components/Vuepress'

const routeItems = [
  ["v-18cc131e","/CHANGELOG.html","Change Log",["/CHANGELOG.md"]],
  ["v-8daa1a0e","/","vuepress-next",["/index.html","/README.md"]],
  ["v-147825fb","/docs/","Home",["/docs/index.html","/docs/README.md"]],
  ["v-9e9bace4","/packages/vuepress/CHANGELOG.html","Change Log",["/packages/vuepress/CHANGELOG.md"]],
  ["v-556acc29","/packages/vuepress-vite/CHANGELOG.html","Change Log",["/packages/vuepress-vite/CHANGELOG.md"]],
  ["v-9377498a","/docs/cosonganh/CT174-Phan_tich_va_thiet_ke_thuat_toan/","Phân tích thiết kế thuật toán",["/docs/cosonganh/CT174-Phan_tich_va_thiet_ke_thuat_toan/index.html","/docs/cosonganh/CT174-Phan_tich_va_thiet_ke_thuat_toan/README.md"]],
  ["v-4f90caae","/docs/cosonganh/CT175-Ly_thuyet_do_thi/","Lý thuyết đồ thị",["/docs/cosonganh/CT175-Ly_thuyet_do_thi/index.html","/docs/cosonganh/CT175-Ly_thuyet_do_thi/README.md"]],
  ["v-02e019c9","/docs/cosonganh/CT176-Lap_trinh_huong_doi_tuong/","Lập trình hướng đối tượng",["/docs/cosonganh/CT176-Lap_trinh_huong_doi_tuong/index.html","/docs/cosonganh/CT176-Lap_trinh_huong_doi_tuong/README.md"]],
  ["v-6a1d447c","/docs/cosonganh/CT177-Cau_truc_du_lieu/","Cấu trúc dữ liệu",["/docs/cosonganh/CT177-Cau_truc_du_lieu/index.html","/docs/cosonganh/CT177-Cau_truc_du_lieu/README.md"]],
  ["v-73b9f21f","/docs/cosonganh/CT178-Nguyen_ly_he_dieu_hanh/","Nguyên lý hệ điều hành",["/docs/cosonganh/CT178-Nguyen_ly_he_dieu_hanh/index.html","/docs/cosonganh/CT178-Nguyen_ly_he_dieu_hanh/README.md"]],
  ["v-9e290e94","/docs/cosonganh/CT179-Quan_tri_he_thong/","Quản trị hệ thống",["/docs/cosonganh/CT179-Quan_tri_he_thong/index.html","/docs/cosonganh/CT179-Quan_tri_he_thong/README.md"]],
  ["v-9a9f60ee","/docs/cosonganh/CT180-Co_so_du_lieu/","Cơ sở dữ liệu",["/docs/cosonganh/CT180-Co_so_du_lieu/index.html","/docs/cosonganh/CT180-Co_so_du_lieu/README.md"]],
  ["v-5a8ec9e3","/docs/cosonganh/CT182-Ngon_ngu_mo_hinh_hoa/","Ngôn ngữ mô hình hóa",["/docs/cosonganh/CT182-Ngon_ngu_mo_hinh_hoa/index.html","/docs/cosonganh/CT182-Ngon_ngu_mo_hinh_hoa/README.md"]],
  ["v-6d91f8fd","/docs/cosonganh/CT296-Phan_tich_thiet_ke_he_thong/","Phân tích thiết kế hệ thống",["/docs/cosonganh/CT296-Phan_tich_thiet_ke_he_thong/index.html","/docs/cosonganh/CT296-Phan_tich_thiet_ke_he_thong/README.md"]],
  ["v-50276514","/docs/doannganh/CT271-Nien_luan_co_so_CNTT/","Niên luận cơ sở CNTT",["/docs/doannganh/CT271-Nien_luan_co_so_CNTT/index.html","/docs/doannganh/CT271-Nien_luan_co_so_CNTT/README.md"]],
  ["v-05bd02a0","/docs/doannganh/CT300-Phat_trien_phan_mem/","Phát triển phần mềm",["/docs/doannganh/CT300-Phat_trien_phan_mem/index.html","/docs/doannganh/CT300-Phat_trien_phan_mem/README.md"]],
  ["v-1c2b3524","/docs/doannganh/CT446-Nien_luan_CNTT/","Niên luận CNTT",["/docs/doannganh/CT446-Nien_luan_CNTT/index.html","/docs/doannganh/CT446-Nien_luan_CNTT/README.md"]],
  ["v-305bd6b6","/docs/doannganh/CT449-Phat_trien_ung_dung_web/","Phát triển ứng dụng Web",["/docs/doannganh/CT449-Phat_trien_ung_dung_web/index.html","/docs/doannganh/CT449-Phat_trien_ung_dung_web/README.md"]],
  ["v-63208969","/docs/doannganh/CT484-Phat_trien_ung_dung_tren_thiet_bi_di_dong/","Phát triển trên ứng dụng thiết bị di động",["/docs/doannganh/CT484-Phat_trien_ung_dung_tren_thiet_bi_di_dong/index.html","/docs/doannganh/CT484-Phat_trien_ung_dung_tren_thiet_bi_di_dong/README.md"]],
  ["v-c2d687a6","/docs/doannganh/CT550-Luan_van_tot_nghiep/","Luận văn tốt nghiệp",["/docs/doannganh/CT550-Luan_van_tot_nghiep/index.html","/docs/doannganh/CT550-Luan_van_tot_nghiep/README.md"]],
  ["v-684a67dc","/docs/chuyennganh/CT222-An_toan_he_thong/","An toàn hệ thống",["/docs/chuyennganh/CT222-An_toan_he_thong/index.html","/docs/chuyennganh/CT222-An_toan_he_thong/README.md"]],
  ["v-7ae17572","/docs/chuyennganh/CT223-Quan_ly_du_an_phan_mem/","Quản lý dự án phần mềm",["/docs/chuyennganh/CT223-Quan_ly_du_an_phan_mem/index.html","/docs/chuyennganh/CT223-Quan_ly_du_an_phan_mem/README.md"]],
  ["v-064f32c2","/docs/chuyennganh/CT273-Giao_dien_nguoi_may/","Giao diện người máy",["/docs/chuyennganh/CT273-Giao_dien_nguoi_may/index.html","/docs/chuyennganh/CT273-Giao_dien_nguoi_may/README.md"]],
  ["v-1f4d7a32","/docs/chuyennganh/CT275-Cong_nghe_web/","Công nghệ Web",["/docs/chuyennganh/CT275-Cong_nghe_web/index.html","/docs/chuyennganh/CT275-Cong_nghe_web/README.md"]],
  ["v-5d0ac9b6","/docs/chuyennganh/CT293-Mang_va_truyen_thong_du_lieu/","Mạng máy tính và truyền thông",["/docs/chuyennganh/CT293-Mang_va_truyen_thong_du_lieu/index.html","/docs/chuyennganh/CT293-Mang_va_truyen_thong_du_lieu/README.md"]],
  ["v-49cab028","/docs/chuyennganh/CT294-May_hoc_ung_dung/","Máy học ứng dụng",["/docs/chuyennganh/CT294-May_hoc_ung_dung/index.html","/docs/chuyennganh/CT294-May_hoc_ung_dung/README.md"]],
  ["v-7856dbd3","/docs/chuyennganh/CT467-Quan_tri_du_lieu/","Quản trị dữ liệu",["/docs/chuyennganh/CT467-Quan_tri_du_lieu/index.html","/docs/chuyennganh/CT467-Quan_tri_du_lieu/README.md"]],
  ["v-6fa1f83e","/docs/nhapmon/CT101-Lap_Trinh_Can_Ban_A/","Lập trình căn bản A",["/docs/nhapmon/CT101-Lap_Trinh_Can_Ban_A/index.html","/docs/nhapmon/CT101-Lap_Trinh_Can_Ban_A/README.md"]],
  ["v-78731ec7","/docs/nhapmon/CT112-Mang_may_tinh/","Mạng máy tính",["/docs/nhapmon/CT112-Mang_may_tinh/index.html","/docs/nhapmon/CT112-Mang_may_tinh/README.md"]],
  ["v-2dadaa0c","/docs/nhapmon/CT172-Toan_roi_rac/","Toán rời rạc",["/docs/nhapmon/CT172-Toan_roi_rac/index.html","/docs/nhapmon/CT172-Toan_roi_rac/README.md"]],
  ["v-f95e4f9a","/docs/nhapmon/CT173-Kien_truc_may_tinh/","Kiến trúc máy tính",["/docs/nhapmon/CT173-Kien_truc_may_tinh/index.html","/docs/nhapmon/CT173-Kien_truc_may_tinh/README.md"]],
  ["v-6beea8ce","/docs/nhapmon/CT188-Nhap_mon_lap_trinh_web/","Nhập môn lập trình Web",["/docs/nhapmon/CT188-Nhap_mon_lap_trinh_web/index.html","/docs/nhapmon/CT188-Nhap_mon_lap_trinh_web/README.md"]],
  ["v-f91b81ec","/docs/nhapmon/CT190-Nhap_mon_tri_tue_nhan_tao/8_puzzle.html","Trò chơi 8-puzzle",["/docs/nhapmon/CT190-Nhap_mon_tri_tue_nhan_tao/8_puzzle.md"]],
  ["v-11d199ec","/docs/nhapmon/CT190-Nhap_mon_tri_tue_nhan_tao/","Nhập môn Trí tuệ nhân tạo",["/docs/nhapmon/CT190-Nhap_mon_tri_tue_nhan_tao/index.html","/docs/nhapmon/CT190-Nhap_mon_tri_tue_nhan_tao/README.md"]],
  ["v-22ab78ce","/docs/nhapmon/CT200-Nen_tang_cong_nghe_thong_tin/","Nền tảng Công Nghệ Thông Tin",["/docs/nhapmon/CT200-Nen_tang_cong_nghe_thong_tin/index.html","/docs/nhapmon/CT200-Nen_tang_cong_nghe_thong_tin/README.md"]],
  ["v-eb0ac1d0","/packages/@vuepress/bundler-vite/CHANGELOG.html","Change Log",["/packages/@vuepress/bundler-vite/CHANGELOG.md"]],
  ["v-008ff0c2","/packages/@vuepress/bundler-webpack/CHANGELOG.html","Change Log",["/packages/@vuepress/bundler-webpack/CHANGELOG.md"]],
  ["v-54e463cf","/packages/@vuepress/cli/CHANGELOG.html","Change Log",["/packages/@vuepress/cli/CHANGELOG.md"]],
  ["v-be8664a4","/packages/@vuepress/client/CHANGELOG.html","Change Log",["/packages/@vuepress/client/CHANGELOG.md"]],
  ["v-37276c9a","/packages/@vuepress/core/CHANGELOG.html","Change Log",["/packages/@vuepress/core/CHANGELOG.md"]],
  ["v-d26baa6c","/packages/@vuepress/markdown/CHANGELOG.html","Change Log",["/packages/@vuepress/markdown/CHANGELOG.md"]],
  ["v-c0b28d5a","/packages/@vuepress/plugin-active-header-links/CHANGELOG.html","Change Log",["/packages/@vuepress/plugin-active-header-links/CHANGELOG.md"]],
  ["v-40869b2c","/packages/@vuepress/plugin-back-to-top/CHANGELOG.html","Change Log",["/packages/@vuepress/plugin-back-to-top/CHANGELOG.md"]],
  ["v-2a530d5c","/packages/@vuepress/plugin-container/CHANGELOG.html","Change Log",["/packages/@vuepress/plugin-container/CHANGELOG.md"]],
  ["v-73c5f8c0","/packages/@vuepress/plugin-debug/CHANGELOG.html","Change Log",["/packages/@vuepress/plugin-debug/CHANGELOG.md"]],
  ["v-361509da","/packages/@vuepress/plugin-docsearch/CHANGELOG.html","Change Log",["/packages/@vuepress/plugin-docsearch/CHANGELOG.md"]],
  ["v-ab1065be","/packages/@vuepress/plugin-git/CHANGELOG.html","Change Log",["/packages/@vuepress/plugin-git/CHANGELOG.md"]],
  ["v-19375fa3","/packages/@vuepress/plugin-google-analytics/CHANGELOG.html","Change Log",["/packages/@vuepress/plugin-google-analytics/CHANGELOG.md"]],
  ["v-da508cb0","/packages/@vuepress/plugin-medium-zoom/CHANGELOG.html","Change Log",["/packages/@vuepress/plugin-medium-zoom/CHANGELOG.md"]],
  ["v-22924c10","/packages/@vuepress/plugin-nprogress/CHANGELOG.html","Change Log",["/packages/@vuepress/plugin-nprogress/CHANGELOG.md"]],
  ["v-1730b7d8","/packages/@vuepress/plugin-palette/CHANGELOG.html","Change Log",["/packages/@vuepress/plugin-palette/CHANGELOG.md"]],
  ["v-451f2229","/packages/@vuepress/plugin-prismjs/CHANGELOG.html","Change Log",["/packages/@vuepress/plugin-prismjs/CHANGELOG.md"]],
  ["v-3f0f6cb9","/packages/@vuepress/plugin-pwa/CHANGELOG.html","Change Log",["/packages/@vuepress/plugin-pwa/CHANGELOG.md"]],
  ["v-2b4e930c","/packages/@vuepress/plugin-pwa-popup/CHANGELOG.html","Change Log",["/packages/@vuepress/plugin-pwa-popup/CHANGELOG.md"]],
  ["v-7bf6c0b3","/packages/@vuepress/plugin-register-components/CHANGELOG.html","Change Log",["/packages/@vuepress/plugin-register-components/CHANGELOG.md"]],
  ["v-57230526","/packages/@vuepress/plugin-search/CHANGELOG.html","Change Log",["/packages/@vuepress/plugin-search/CHANGELOG.md"]],
  ["v-6bbeec21","/packages/@vuepress/plugin-shiki/CHANGELOG.html","Change Log",["/packages/@vuepress/plugin-shiki/CHANGELOG.md"]],
  ["v-83c066b2","/packages/@vuepress/plugin-theme-data/CHANGELOG.html","Change Log",["/packages/@vuepress/plugin-theme-data/CHANGELOG.md"]],
  ["v-e1a87e2a","/packages/@vuepress/plugin-toc/CHANGELOG.html","Change Log",["/packages/@vuepress/plugin-toc/CHANGELOG.md"]],
  ["v-6ac38dd4","/packages/@vuepress/shared/CHANGELOG.html","Change Log",["/packages/@vuepress/shared/CHANGELOG.md"]],
  ["v-883da95c","/packages/@vuepress/theme-default/CHANGELOG.html","Change Log",["/packages/@vuepress/theme-default/CHANGELOG.md"]],
  ["v-68ca455e","/packages/@vuepress/utils/CHANGELOG.html","Change Log",["/packages/@vuepress/utils/CHANGELOG.md"]],
  ["v-1ff51956","/docs/nhapmon/CT101-Lap_Trinh_Can_Ban_A/Source/","Source Code C",["/docs/nhapmon/CT101-Lap_Trinh_Can_Ban_A/Source/index.html","/docs/nhapmon/CT101-Lap_Trinh_Can_Ban_A/Source/README.md"]],
  ["v-64192e0e","/docs/cosonganh/CT177-Cau_truc_du_lieu/Source/Linked%20List/","Danh sách Liên kết:",["/docs/cosonganh/CT177-Cau_truc_du_lieu/Source/Linked List/","/docs/cosonganh/CT177-Cau_truc_du_lieu/Source/Linked%20List/index.html","/docs/cosonganh/CT177-Cau_truc_du_lieu/Source/Linked List/README.md","/docs/cosonganh/CT177-Cau_truc_du_lieu/Source/Linked%20List/README.md"]],
  ["v-aeb66da8","/docs/nhapmon/CT101-Lap_Trinh_Can_Ban_A/Source/Array/Array.html","",["/docs/nhapmon/CT101-Lap_Trinh_Can_Ban_A/Source/Array/Array.md"]],
  ["v-4abd05ec","/docs/nhapmon/CT101-Lap_Trinh_Can_Ban_A/Source/Array/","Nhấn vào đây để xem chi tiết",["/docs/nhapmon/CT101-Lap_Trinh_Can_Ban_A/Source/Array/index.html","/docs/nhapmon/CT101-Lap_Trinh_Can_Ban_A/Source/Array/README.md"]],
  ["v-7c50792a","/docs/nhapmon/CT101-Lap_Trinh_Can_Ban_A/Source/Ctype/Ctype.h.html","Ctype.h",["/docs/nhapmon/CT101-Lap_Trinh_Can_Ban_A/Source/Ctype/Ctype.h.md"]],
  ["v-4e464aa8","/docs/nhapmon/CT101-Lap_Trinh_Can_Ban_A/Source/Ctype/","Nhấn vào đây để xem chi tiết",["/docs/nhapmon/CT101-Lap_Trinh_Can_Ban_A/Source/Ctype/index.html","/docs/nhapmon/CT101-Lap_Trinh_Can_Ban_A/Source/Ctype/README.md"]],
  ["v-d4b7f828","/docs/nhapmon/CT101-Lap_Trinh_Can_Ban_A/Source/Data%20Structures/Data%20Structures.html","Data Structures",["/docs/nhapmon/CT101-Lap_Trinh_Can_Ban_A/Source/Data Structures/Data Structures.html","/docs/nhapmon/CT101-Lap_Trinh_Can_Ban_A/Source/Data Structures/Data Structures.md","/docs/nhapmon/CT101-Lap_Trinh_Can_Ban_A/Source/Data%20Structures/Data%20Structures.md"]],
  ["v-163c67cc","/docs/nhapmon/CT101-Lap_Trinh_Can_Ban_A/Source/Data%20Structures/","Nhấn vào đây để xem chi tiết",["/docs/nhapmon/CT101-Lap_Trinh_Can_Ban_A/Source/Data Structures/","/docs/nhapmon/CT101-Lap_Trinh_Can_Ban_A/Source/Data%20Structures/index.html","/docs/nhapmon/CT101-Lap_Trinh_Can_Ban_A/Source/Data Structures/README.md","/docs/nhapmon/CT101-Lap_Trinh_Can_Ban_A/Source/Data%20Structures/README.md"]],
  ["v-28cc3e74","/docs/nhapmon/CT101-Lap_Trinh_Can_Ban_A/Source/File%20Handling/File%20Handling.html","File Handling",["/docs/nhapmon/CT101-Lap_Trinh_Can_Ban_A/Source/File Handling/File Handling.html","/docs/nhapmon/CT101-Lap_Trinh_Can_Ban_A/Source/File Handling/File Handling.md","/docs/nhapmon/CT101-Lap_Trinh_Can_Ban_A/Source/File%20Handling/File%20Handling.md"]],
  ["v-a789a20e","/docs/nhapmon/CT101-Lap_Trinh_Can_Ban_A/Source/File%20Handling/","Nhấn vào đây để xem chi tiết",["/docs/nhapmon/CT101-Lap_Trinh_Can_Ban_A/Source/File Handling/","/docs/nhapmon/CT101-Lap_Trinh_Can_Ban_A/Source/File%20Handling/index.html","/docs/nhapmon/CT101-Lap_Trinh_Can_Ban_A/Source/File Handling/README.md","/docs/nhapmon/CT101-Lap_Trinh_Can_Ban_A/Source/File%20Handling/README.md"]],
  ["v-ed25605c","/docs/nhapmon/CT101-Lap_Trinh_Can_Ban_A/Source/Formula/Formula.html","Formula",["/docs/nhapmon/CT101-Lap_Trinh_Can_Ban_A/Source/Formula/Formula.md"]],
  ["v-0e22ba02","/docs/nhapmon/CT101-Lap_Trinh_Can_Ban_A/Source/Formula/","Nhấn vào đây để xem chi tiết",["/docs/nhapmon/CT101-Lap_Trinh_Can_Ban_A/Source/Formula/index.html","/docs/nhapmon/CT101-Lap_Trinh_Can_Ban_A/Source/Formula/README.md"]],
  ["v-c9dbfa40","/docs/nhapmon/CT101-Lap_Trinh_Can_Ban_A/Source/Function/Function.html","Function",["/docs/nhapmon/CT101-Lap_Trinh_Can_Ban_A/Source/Function/Function.md"]],
  ["v-a117a2be","/docs/nhapmon/CT101-Lap_Trinh_Can_Ban_A/Source/Function/","Nhấn vào đây để xem chi tiết",["/docs/nhapmon/CT101-Lap_Trinh_Can_Ban_A/Source/Function/index.html","/docs/nhapmon/CT101-Lap_Trinh_Can_Ban_A/Source/Function/README.md"]],
  ["v-819845c0","/docs/nhapmon/CT101-Lap_Trinh_Can_Ban_A/Source/Game/Game.html","Game",["/docs/nhapmon/CT101-Lap_Trinh_Can_Ban_A/Source/Game/Game.md"]],
  ["v-5dace272","/docs/nhapmon/CT101-Lap_Trinh_Can_Ban_A/Source/Game/","Nhấn vào đây để xem chi tiết",["/docs/nhapmon/CT101-Lap_Trinh_Can_Ban_A/Source/Game/index.html","/docs/nhapmon/CT101-Lap_Trinh_Can_Ban_A/Source/Game/README.md"]],
  ["v-a9921780","/docs/nhapmon/CT101-Lap_Trinh_Can_Ban_A/Source/Miscellaneus/Miscellaneus.html","Miscellaneus",["/docs/nhapmon/CT101-Lap_Trinh_Can_Ban_A/Source/Miscellaneus/Miscellaneus.md"]],
  ["v-4ea9ac3c","/docs/nhapmon/CT101-Lap_Trinh_Can_Ban_A/Source/Miscellaneus/","Nhấn vào đây để xem chi tiết",["/docs/nhapmon/CT101-Lap_Trinh_Can_Ban_A/Source/Miscellaneus/index.html","/docs/nhapmon/CT101-Lap_Trinh_Can_Ban_A/Source/Miscellaneus/README.md"]],
  ["v-2827f500","/docs/nhapmon/CT101-Lap_Trinh_Can_Ban_A/Source/Graphics/Graphics.html","Graphics",["/docs/nhapmon/CT101-Lap_Trinh_Can_Ban_A/Source/Graphics/Graphics.md"]],
  ["v-71e9ce4e","/docs/nhapmon/CT101-Lap_Trinh_Can_Ban_A/Source/Graphics/","Nhấn vào đây để xem chi tiết",["/docs/nhapmon/CT101-Lap_Trinh_Can_Ban_A/Source/Graphics/index.html","/docs/nhapmon/CT101-Lap_Trinh_Can_Ban_A/Source/Graphics/README.md"]],
  ["v-23d0b140","/docs/nhapmon/CT101-Lap_Trinh_Can_Ban_A/Source/Number/Number.html","Number",["/docs/nhapmon/CT101-Lap_Trinh_Can_Ban_A/Source/Number/Number.md"]],
  ["v-7d260060","/docs/nhapmon/CT101-Lap_Trinh_Can_Ban_A/Source/Number/","Nhấn vào đây để xem chi tiết",["/docs/nhapmon/CT101-Lap_Trinh_Can_Ban_A/Source/Number/index.html","/docs/nhapmon/CT101-Lap_Trinh_Can_Ban_A/Source/Number/README.md"]],
  ["v-fa398c04","/docs/nhapmon/CT101-Lap_Trinh_Can_Ban_A/Source/Pattern/Pattern.html","Pattern",["/docs/nhapmon/CT101-Lap_Trinh_Can_Ban_A/Source/Pattern/Pattern.md"]],
  ["v-26e84e15","/docs/nhapmon/CT101-Lap_Trinh_Can_Ban_A/Source/Pattern/","Nhấn vào đây để xem chi tiết",["/docs/nhapmon/CT101-Lap_Trinh_Can_Ban_A/Source/Pattern/index.html","/docs/nhapmon/CT101-Lap_Trinh_Can_Ban_A/Source/Pattern/README.md"]],
  ["v-33e6b9e4","/docs/nhapmon/CT101-Lap_Trinh_Can_Ban_A/Source/Pointer/Pointer.html","Pointer",["/docs/nhapmon/CT101-Lap_Trinh_Can_Ban_A/Source/Pointer/Pointer.md"]],
  ["v-0f275df0","/docs/nhapmon/CT101-Lap_Trinh_Can_Ban_A/Source/Pointer/","Nhấn vào đây để xem chi tiết",["/docs/nhapmon/CT101-Lap_Trinh_Can_Ban_A/Source/Pointer/index.html","/docs/nhapmon/CT101-Lap_Trinh_Can_Ban_A/Source/Pointer/README.md"]],
  ["v-a64069fa","/docs/nhapmon/CT101-Lap_Trinh_Can_Ban_A/Source/Recursion/","Nhấn vào đây để xem chi tiết",["/docs/nhapmon/CT101-Lap_Trinh_Can_Ban_A/Source/Recursion/index.html","/docs/nhapmon/CT101-Lap_Trinh_Can_Ban_A/Source/Recursion/README.md"]],
  ["v-6b77409a","/docs/nhapmon/CT101-Lap_Trinh_Can_Ban_A/Source/Recursion/Recursion.html","Recursion",["/docs/nhapmon/CT101-Lap_Trinh_Can_Ban_A/Source/Recursion/Recursion.md"]],
  ["v-5c4dcaca","/docs/nhapmon/CT101-Lap_Trinh_Can_Ban_A/Source/Sort/","Nhấn vào đây để xem chi tiết",["/docs/nhapmon/CT101-Lap_Trinh_Can_Ban_A/Source/Sort/index.html","/docs/nhapmon/CT101-Lap_Trinh_Can_Ban_A/Source/Sort/README.md"]],
  ["v-043fe1a0","/docs/nhapmon/CT101-Lap_Trinh_Can_Ban_A/Source/Sort/Sort.html","Sort",["/docs/nhapmon/CT101-Lap_Trinh_Can_Ban_A/Source/Sort/Sort.md"]],
  ["v-6efdd7f0","/docs/nhapmon/CT101-Lap_Trinh_Can_Ban_A/Source/String/","Nhấn vào đây để xem chi tiết",["/docs/nhapmon/CT101-Lap_Trinh_Can_Ban_A/Source/String/index.html","/docs/nhapmon/CT101-Lap_Trinh_Can_Ban_A/Source/String/README.md"]],
  ["v-9bf8fb80","/docs/nhapmon/CT101-Lap_Trinh_Can_Ban_A/Source/String/String.html","String",["/docs/nhapmon/CT101-Lap_Trinh_Can_Ban_A/Source/String/String.md"]],
  ["v-00c2cc74","/docs/nhapmon/CT112-Mang_may_tinh/Tailieu/Chapter1/1.html","Bài 1: Mạng điện báo",["/docs/nhapmon/CT112-Mang_may_tinh/Tailieu/Chapter1/1.md"]],
  ["v-01537265","/docs/nhapmon/CT112-Mang_may_tinh/Tailieu/Chapter1/2.html","Bài 2: Mạng điện thoại:",["/docs/nhapmon/CT112-Mang_may_tinh/Tailieu/Chapter1/2.md"]],
  ["v-03084b04","/docs/nhapmon/CT112-Mang_may_tinh/Tailieu/Chapter1/3.html","Bài 3: Mạng hướng đầu cuối",["/docs/nhapmon/CT112-Mang_may_tinh/Tailieu/Chapter1/3.md"]],
  ["v-04bd23a3","/docs/nhapmon/CT112-Mang_may_tinh/Tailieu/Chapter1/4.html","Bài 4: Mạng máy tính",["/docs/nhapmon/CT112-Mang_may_tinh/Tailieu/Chapter1/4.md"]],
  ["v-677fc6a5","/docs/nhapmon/CT112-Mang_may_tinh/Tailieu/Chapter2/1.html","Bài 1: Phân loại MTT theo kỹ thuật",["/docs/nhapmon/CT112-Mang_may_tinh/Tailieu/Chapter2/1.md"]],
  ["v-69349f44","/docs/nhapmon/CT112-Mang_may_tinh/Tailieu/Chapter2/2.html","Bài 2:Phân loại MTT theo phạm vi",["/docs/nhapmon/CT112-Mang_may_tinh/Tailieu/Chapter2/2.md"]],
  ["v-6ae977e3","/docs/nhapmon/CT112-Mang_may_tinh/Tailieu/Chapter2/3.html","Bài 3: Mạng không dây và liên mạng",["/docs/nhapmon/CT112-Mang_may_tinh/Tailieu/Chapter2/3.md"]],
  ["v-6c9e5082","/docs/nhapmon/CT112-Mang_may_tinh/Tailieu/Chapter2/4.html","Bài 4: Các phần mềm và dịch vụ mạng",["/docs/nhapmon/CT112-Mang_may_tinh/Tailieu/Chapter2/4.md"]],
  ["v-6e532921","/docs/nhapmon/CT112-Mang_may_tinh/Tailieu/Chapter2/5.html","Bài 5: Mô hình OSI",["/docs/nhapmon/CT112-Mang_may_tinh/Tailieu/Chapter2/5.md"]],
  ["v-613e18f8","/docs/nhapmon/CT112-Mang_may_tinh/Tailieu/Chapter3/1.html","Bài 1: Vấn đề số hóa thông tin",["/docs/nhapmon/CT112-Mang_may_tinh/Tailieu/Chapter3/1.md"]],
  ["v-5dd467ba","/docs/nhapmon/CT112-Mang_may_tinh/Tailieu/Chapter3/2.html","Bài 2: Các loại kênh truyền",["/docs/nhapmon/CT112-Mang_may_tinh/Tailieu/Chapter3/2.md"]],
  ["v-5a6ab67c","/docs/nhapmon/CT112-Mang_may_tinh/Tailieu/Chapter3/3.html","Bài 3: Đặc điểm kênh truyền",["/docs/nhapmon/CT112-Mang_may_tinh/Tailieu/Chapter3/3.md"]],
  ["v-5701053e","/docs/nhapmon/CT112-Mang_may_tinh/Tailieu/Chapter3/4.html","Bài 4: Mã hóa đường truyền",["/docs/nhapmon/CT112-Mang_may_tinh/Tailieu/Chapter3/4.md"]],
  ["v-37422063","/docs/nhapmon/CT112-Mang_may_tinh/Tailieu/Chapter4/1.html","Bài 1: Chức năng của tầng liên kết dữ liệu",["/docs/nhapmon/CT112-Mang_may_tinh/Tailieu/Chapter4/1.md"]],
  ["v-38f6f902","/docs/nhapmon/CT112-Mang_may_tinh/Tailieu/Chapter4/2.html","Bài 2: Vấn đề xử lý lỗi",["/docs/nhapmon/CT112-Mang_may_tinh/Tailieu/Chapter4/2.md"]],
  ["v-3aabd1a1","/docs/nhapmon/CT112-Mang_may_tinh/Tailieu/Chapter4/3.html","Bài 3: Một số giao thức Error Control",["/docs/nhapmon/CT112-Mang_may_tinh/Tailieu/Chapter4/3.md"]],
  ["v-3c60aa40","/docs/nhapmon/CT112-Mang_may_tinh/Tailieu/Chapter4/4.html","Bài 4: Giao thức của Sliding Windows",["/docs/nhapmon/CT112-Mang_may_tinh/Tailieu/Chapter4/4.md"]],
  ["v-c1b9657c","/docs/nhapmon/CT112-Mang_may_tinh/Tailieu/Chapter5/1.html","Bài 1: Tổng quan về LAN",["/docs/nhapmon/CT112-Mang_may_tinh/Tailieu/Chapter5/1.md"]],
  ["v-be4fb43e","/docs/nhapmon/CT112-Mang_may_tinh/Tailieu/Chapter5/2.html","Bài 2: Các hình thái mạng",["/docs/nhapmon/CT112-Mang_may_tinh/Tailieu/Chapter5/2.md"]],
  ["v-bae60300","/docs/nhapmon/CT112-Mang_may_tinh/Tailieu/Chapter5/3.html","Bài 3: Lớp con MAC",["/docs/nhapmon/CT112-Mang_may_tinh/Tailieu/Chapter5/3.md"]],
  ["v-b77c51c2","/docs/nhapmon/CT112-Mang_may_tinh/Tailieu/Chapter5/4.html","Bài 4: Chuẩn hóa mạng cục bộ",["/docs/nhapmon/CT112-Mang_may_tinh/Tailieu/Chapter5/4.md"]],
  ["v-b412a084","/docs/nhapmon/CT112-Mang_may_tinh/Tailieu/Chapter5/5.html","Bài 5: Một số công nghệ LAN",["/docs/nhapmon/CT112-Mang_may_tinh/Tailieu/Chapter5/5.md"]],
  ["v-07047a21","/docs/nhapmon/CT112-Mang_may_tinh/Tailieu/Chapter6/1.html","Bài 1: Giới thiệu NetWork Layer",["/docs/nhapmon/CT112-Mang_may_tinh/Tailieu/Chapter6/1.md"]],
  ["v-08b952c0","/docs/nhapmon/CT112-Mang_may_tinh/Tailieu/Chapter6/2.html","Bài 2: Các vấn đề về thiết kế tầng mạng",["/docs/nhapmon/CT112-Mang_may_tinh/Tailieu/Chapter6/2.md"]],
  ["v-0a6e2b5f","/docs/nhapmon/CT112-Mang_may_tinh/Tailieu/Chapter6/3.html","Bài 3: Giải thuật chọn đường",["/docs/nhapmon/CT112-Mang_may_tinh/Tailieu/Chapter6/3.md"]],
  ["v-0c2303fe","/docs/nhapmon/CT112-Mang_may_tinh/Tailieu/Chapter6/4.html","Bài 4: Các vấn đề chống tắc nghẽn",["/docs/nhapmon/CT112-Mang_may_tinh/Tailieu/Chapter6/4.md"]],
  ["v-0dd7dc9d","/docs/nhapmon/CT112-Mang_may_tinh/Tailieu/Chapter6/5.html","Bài 5: Liên mạng",["/docs/nhapmon/CT112-Mang_may_tinh/Tailieu/Chapter6/5.md"]],
  ["v-0f8cb53c","/docs/nhapmon/CT112-Mang_may_tinh/Tailieu/Chapter6/6.html","Bài 6: Bộ giao thức liên mạng",["/docs/nhapmon/CT112-Mang_may_tinh/Tailieu/Chapter6/6.md"]],
  ["v-6ee5a700","/docs/nhapmon/CT112-Mang_may_tinh/Tailieu/Chapter7/1.html","Bài 1: Dịch vụ của tầng vận chuyển",["/docs/nhapmon/CT112-Mang_may_tinh/Tailieu/Chapter7/1.md"]],
  ["v-709a7f9f","/docs/nhapmon/CT112-Mang_may_tinh/Tailieu/Chapter7/2.html","Bài 2: Các yếu tố cấu thành giao thức vận chuyển",["/docs/nhapmon/CT112-Mang_may_tinh/Tailieu/Chapter7/2.md"]],
  ["v-724f583e","/docs/nhapmon/CT112-Mang_may_tinh/Tailieu/Chapter7/3.html","Bài 3: Tầng vận chuyển trong mạng Internet",["/docs/nhapmon/CT112-Mang_may_tinh/Tailieu/Chapter7/3.md"]],
  ["v-52725842","/docs/nhapmon/CT112-Mang_may_tinh/Tailieu/Chapter8/1.html","Bài 1: Dịch vụ DNS",["/docs/nhapmon/CT112-Mang_may_tinh/Tailieu/Chapter8/1.md"]],
  ["v-4f08a704","/docs/nhapmon/CT112-Mang_may_tinh/Tailieu/Chapter8/2.html","Bài 2: Electronic Mail (SMTP, MINE, POP3...)",["/docs/nhapmon/CT112-Mang_may_tinh/Tailieu/Chapter8/2.md"]],
  ["v-4b9ef5c6","/docs/nhapmon/CT112-Mang_may_tinh/Tailieu/Chapter8/3.html","Bài 3: World Wide Web (HTTP)",["/docs/nhapmon/CT112-Mang_may_tinh/Tailieu/Chapter8/3.md"]],
  ["v-48354488","/docs/nhapmon/CT112-Mang_may_tinh/Tailieu/Chapter8/4.html","Bài 4: Truyền tập tin (FTP)",["/docs/nhapmon/CT112-Mang_may_tinh/Tailieu/Chapter8/4.md"]],
  ["v-4fe7eaf5","/packages/@vuepress/markdown/__tests__/__fixtures__/importCode.html","msg",["/packages/@vuepress/markdown/__tests__/__fixtures__/importCode.md"]],
  ["v-deac0c70","/packages/@vuepress/utils/node_modules/debug/","debug",["/packages/@vuepress/utils/node_modules/debug/index.html","/packages/@vuepress/utils/node_modules/debug/README.md"]],
  ["v-7c51f6f5","/packages/@vuepress/utils/node_modules/ms/license.html","",["/packages/@vuepress/utils/node_modules/ms/license.md"]],
  ["v-434ead3d","/packages/@vuepress/utils/node_modules/ms/","ms",["/packages/@vuepress/utils/node_modules/ms/index.html","/packages/@vuepress/utils/node_modules/ms/readme.md"]],
  ["v-3c644af3","/packages/@vuepress/core/__tests__/__fixtures__/pages/bar.html","bar frontmatter",["/packages/@vuepress/core/__tests__/__fixtures__/pages/bar.md"]],
  ["v-893c9bc0","/packages/@vuepress/core/__tests__/__fixtures__/pages/foo.html","foo frontmatter",["/packages/@vuepress/core/__tests__/__fixtures__/pages/foo.md"]],
  ["v-5b98e754","/packages/@vuepress/core/__tests__/__fixtures__/pages-with-404/404.html","",["/packages/@vuepress/core/__tests__/__fixtures__/pages-with-404/404.md"]],
  ["v-e026754e","/packages/@vuepress/core/__tests__/__fixtures__/pages-with-404/bar.html","bar frontmatter",["/packages/@vuepress/core/__tests__/__fixtures__/pages-with-404/bar.md"]],
  ["v-0eea2c86","/packages/@vuepress/core/__tests__/__fixtures__/pages-with-404/foo.html","foo frontmatter",["/packages/@vuepress/core/__tests__/__fixtures__/pages-with-404/foo.md"]],
  ["v-3706649a","/404.html","",[]],
]

export const pagesRoutes = routeItems.reduce(
  (result, [name, path, title, redirects]) => {
    result.push(
      {
        name,
        path,
        component: Vuepress,
        meta: { title },
      },
      ...redirects.map((item) => ({
        path: item,
        redirect: path,
      }))
    )
    return result
  },
  [
    {
      name: "404",
      path: "/:catchAll(.*)",
      component: Vuepress,
    }
  ]
)
