<template><h2 id="🌀-đay-la-phan-mau-pattern-tong-hop-cac-dang-ve-mau-va-hinh-hoc-🌀" tabindex="-1"><a class="header-anchor" href="#🌀-đay-la-phan-mau-pattern-tong-hop-cac-dang-ve-mau-va-hinh-hoc-🌀" aria-hidden="true">#</a> 🌀 Đây là phần mẫu (<code>Pattern</code>) tổng hợp các dạng vẽ mẫu và hình học 🌀</h2>
<h1 id="nhan-vao-đay-đe-xem-chi-tiet" tabindex="-1"><a class="header-anchor" href="#nhan-vao-đay-đe-xem-chi-tiet" aria-hidden="true">#</a> <a href="https://github.com/Zenfection/Source_Code_C/blob/master/Pattern/Pattern.md" target="_blank" rel="noopener noreferrer"><img src="https://raw.githubusercontent.com/Zenfection/Image/master/2020/08/23-21-29-53-icons8_curved_arrow_64px_1.png" alt="icons8_curved_arrow_64px_1.png"> Nhấn vào đây để xem chi tiết<OutboundLink/></a></h1>
<h2 id="chi-tiet-cac-bai" tabindex="-1"><a class="header-anchor" href="#chi-tiet-cac-bai" aria-hidden="true">#</a> <img src="https://raw.githubusercontent.com/Zenfection/Image/master/2020/08/23-21-54-43-icons8_list_64px_1.png" title="" alt="icons8_list_64px_1.png" width="50">Chi tiết các bài:</h2>
<ol>
<li><a href="https://github.com/Zenfection/Source_Code_C/blob/master/Pattern/Pattern.md#1-m%E1%BA%ABu-nh%E1%BB%8B-ph%C3%A2n-binary-pattern" target="_blank" rel="noopener noreferrer">Mẫu nhị phân<OutboundLink/></a></li>
<li><a href="https://github.com/Zenfection/Source_Code_C/blob/master/Pattern/Pattern.md#2-m%E1%BA%ABu-kim-c%C6%B0%C6%A1ng-diamond-pattern" target="_blank" rel="noopener noreferrer">Mẫu kim cương<OutboundLink/></a></li>
<li><a href="https://github.com/Zenfection/Source_Code_C/blob/master/Pattern/Pattern.md#3-m%E1%BA%ABu-s%E1%BB%91-kim-c%C6%B0%C6%A1ng-diamond-of-number-pattern" target="_blank" rel="noopener noreferrer">Mẫu số kim cương<OutboundLink/></a></li>
<li><a href="https://github.com/Zenfection/Source_Code_C/blob/master/Pattern/Pattern.md#4-m%E1%BA%ABu-sao-kim-c%C6%B0%C6%A1ng-star-diamond-pattern" target="_blank" rel="noopener noreferrer">Mẫu sao kim cương<OutboundLink/></a></li>
<li><a href="https://github.com/Zenfection/Source_Code_C/blob/master/Pattern/Pattern.md#5tam-gi%C3%A1c-floyds-floys-triangle" target="_blank" rel="noopener noreferrer">Tam giác Floyds<OutboundLink/></a></li>
<li><a href="https://github.com/Zenfection/Source_Code_C/blob/master/Pattern/Pattern.md#6-kim-c%C6%B0%C6%A1ng-r%E1%BB%97ng-hollow-diamond" target="_blank" rel="noopener noreferrer">Kim cương rỗng<OutboundLink/></a></li>
<li><a href="https://github.com/Zenfection/Source_Code_C/blob/master/Pattern/Pattern.md#7-h%C3%ACnh-vu%C3%B4ng-r%C3%B5ng-hollow-square" target="_blank" rel="noopener noreferrer">Hình vương rỗng<OutboundLink/></a></li>
<li><a href="https://github.com/Zenfection/Source_Code_C/blob/master/Pattern/Pattern.md#8-m%E1%BA%ABu-%C4%91%E1%BB%93ng-h%E1%BB%93-c%C3%A1t-hourglass-pattern" target="_blank" rel="noopener noreferrer">Mẫu đồng hồ cát<OutboundLink/></a></li>
<li><a href="https://github.com/Zenfection/Source_Code_C/blob/master/Pattern/Pattern.md#9-m%E1%BA%ABu-s%E1%BB%91-ch%E1%BB%AF-c%C3%A1i-number-alphabet-pattern" target="_blank" rel="noopener noreferrer">Mẫu số chữ cái<OutboundLink/></a></li>
<li><a href="https://github.com/Zenfection/Source_Code_C/blob/master/Pattern/Pattern.md#10-m%E1%BA%ABu-s%E1%BB%91-kim-c%C6%B0%C6%A1ng-number-diamond-pattern" target="_blank" rel="noopener noreferrer">Mẫu số kim cương<OutboundLink/></a></li>
<li><a href="https://github.com/Zenfection/Source_Code_C/blob/master/Pattern/Pattern.md#11-m%E1%BA%ABu-h%C3%ACnh-ch%E1%BB%AF-nh%E1%BA%ADt-lo%E1%BA%A1i-1-rectangle-pattern-1" target="_blank" rel="noopener noreferrer">Mẫu hình chữ nhật loại 1<OutboundLink/></a></li>
<li><a href="https://github.com/Zenfection/Source_Code_C/blob/master/Pattern/Pattern.md#12-m%E1%BA%ABu-s%E1%BB%91-lo%E1%BA%A1i-1-number-pattern-1" target="_blank" rel="noopener noreferrer">Mẫu số loại 1<OutboundLink/></a></li>
<li><a href="https://github.com/Zenfection/Source_Code_C/blob/master/Pattern/Pattern.md#13-m%E1%BA%ABu-s%E1%BB%91-lo%E1%BA%A1i-2-number-pattern-2" target="_blank" rel="noopener noreferrer">Mẫu số loại 2<OutboundLink/></a></li>
<li><a href="https://github.com/Zenfection/Source_Code_C/blob/master/Pattern/Pattern.md#14-m%E1%BA%ABu-s%E1%BB%91-lo%E1%BA%A1i-3-number-pattern-3" target="_blank" rel="noopener noreferrer">Mẫu số loại 3<OutboundLink/></a></li>
<li><a href="https://github.com/Zenfection/Source_Code_C/blob/master/Pattern/Pattern.md#15-m%E1%BA%ABu-s%E1%BB%91-lo%E1%BA%A1i-4-number-pattern-4" target="_blank" rel="noopener noreferrer">Mẫu số loại 4<OutboundLink/></a></li>
<li><a href="https://github.com/Zenfection/Source_Code_C/blob/master/Pattern/Pattern.md#16-kim-t%E1%BB%B1-th%C3%A1p-s%E1%BB%91-number-pyramid" target="_blank" rel="noopener noreferrer">Kim tự tháp số<OutboundLink/></a></li>
<li><a href="https://github.com/Zenfection/Source_Code_C/blob/master/Pattern/Pattern.md#17tam-gi%C3%A1c-pascal-kh%C3%B4ng-s%E1%BB%AD-d%E1%BB%A5ng-h%C3%A0m-ri%C3%AAng-pascals-triangle-without-using-function" target="_blank" rel="noopener noreferrer">Tam giác Pascal không sử dụng hàm riêng<OutboundLink/></a></li>
<li><a href="https://github.com/Zenfection/Source_Code_C/blob/master/Pattern/Pattern.md#18-m%E1%BA%ABu-lo%E1%BA%A1i-1-pattern-1" target="_blank" rel="noopener noreferrer">Mẫu loại 1<OutboundLink/></a></li>
<li><a href="https://github.com/Zenfection/Source_Code_C/blob/master/Pattern/Pattern.md#19-m%E1%BA%ABu-lo%E1%BA%A1i-2-pattern-2" target="_blank" rel="noopener noreferrer">Mẫu loại 2<OutboundLink/></a></li>
<li><a href="https://github.com/Zenfection/Source_Code_C/blob/master/Pattern/Pattern.md#20-m%E1%BA%ABu-lo%E1%BA%A1i-3-pattern-3" target="_blank" rel="noopener noreferrer">Mẫu loại 3<OutboundLink/></a></li>
<li><a href="https://github.com/Zenfection/Source_Code_C/blob/master/Pattern/Pattern.md#21-m%E1%BA%ABu-lo%E1%BA%A1i-4-pattern-4" target="_blank" rel="noopener noreferrer">Mẫu loại 4<OutboundLink/></a></li>
<li><a href="https://github.com/Zenfection/Source_Code_C/blob/master/Pattern/Pattern.md#22-m%E1%BA%ABu-lo%E1%BA%A1i-5-pattern-5" target="_blank" rel="noopener noreferrer">Mẫu loại 5<OutboundLink/></a></li>
<li><a href="https://github.com/Zenfection/Source_Code_C/blob/master/Pattern/Pattern.md#23-m%E1%BA%ABu-lo%E1%BA%A1i-6-pattern-6" target="_blank" rel="noopener noreferrer">Mẫu loại 6<OutboundLink/></a></li>
<li><a href="https://github.com/Zenfection/Source_Code_C/blob/master/Pattern/Pattern.md#24-m%E1%BA%ABu-lo%E1%BA%A1i-7-pattern-7" target="_blank" rel="noopener noreferrer">Mẫu loại 7<OutboundLink/></a></li>
<li><a href="https://github.com/Zenfection/Source_Code_C/blob/master/Pattern/Pattern.md#25-kim-t%E1%BB%B1-th%C3%A1p-pyramid" target="_blank" rel="noopener noreferrer">Kim tự tháp<OutboundLink/></a></li>
<li><a href="https://github.com/Zenfection/Source_Code_C/blob/master/Pattern/Pattern.md#26-m%E1%BA%ABu-tam-gi%C3%A1c-ng%C6%B0%E1%BB%A3c-reverse-triangle-pattern" target="_blank" rel="noopener noreferrer">Mẫu tam giác ngược<OutboundLink/></a></li>
<li><a href="https://github.com/Zenfection/Source_Code_C/blob/master/Pattern/Pattern.md#27m%E1%BA%ABu-h%C3%ACnh-thoi-rhombus-pattern" target="_blank" rel="noopener noreferrer">Mẫu hình thoi<OutboundLink/></a></li>
<li><a href="https://github.com/Zenfection/Source_Code_C/blob/master/Pattern/Pattern.md#28-tam-gi%C3%A1c-ch%E1%BB%89-c%C3%B3-%C4%91%C6%B0%E1%BB%9Dng-vi%E1%BB%81n-triangle-with-only-border" target="_blank" rel="noopener noreferrer">Tam giác chỉ có đường viền<OutboundLink/></a></li>
<li><a href="https://github.com/Zenfection/Source_Code_C/blob/master/Pattern/Pattern.md#29-m%E1%BA%ABu-x-x-pattern" target="_blank" rel="noopener noreferrer">Mẫu X<OutboundLink/></a></li>
</ol>
</template>
